baseURL: https://www.kevinmingtarja.com/
languageCode: en-us
title: Kevin Mingtarja
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Kevin Mingtarja
  description: My Home on the Internet
  keywords: [Blog, Portfolio]
  author: Kevin Mingtarja
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  #   ShowPostNavLinks: true
  #   ShowBreadCrumbs: true
  #   ShowCodeCopyButtons: false
  # ShowWordCount: true
  #   ShowRssButtonInSectionTermList: true
  #   UseHugoToc: true
  #   disableSpecial1stPost: false
  #   disableScrollToTop: false
  #   comments: false
  #   hidemeta: false
  #   hideSummary: false
  #   showtoc: false
  #   tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon.ico"
    favicon32x32: "/favicon.ico"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  #   label:
  #     text: "Home"
  #     icon: /apple-touch-icon.png
  #     iconHeight: 35

  #   # profile-mode
  #   profileMode:
  #     enabled: false # needs to be explicitly set
  #     title: ExampleSite
  #     subtitle: "This is subtitle"
  #     imageUrl: "<img location>"
  #     imageWidth: 120
  #     imageHeight: 120
  #     imageTitle: my image
  #     buttons:
  #       - name: Posts
  #         url: posts
  #       - name: Tags
  #         url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: |
      I'm Kevin, a computer science undergrad at the National University of Singapore.
      I have a particular interest towards data infrastrucuture, networking, distributed systems, as well as infrastructure and ops. 
      And in this blog, I write about my exploration, learnings, and thoughts on these topics.
      &nbsp; 

      &nbsp; 

      Currently, I’m working on [Hypermode](https://hypermode.com/), a platform that helps developers build AI into their applications.
      And on my free time, I contribute to open source projects related to databases and cloud infrastructure such as ClickHouse, CockroachDB, KServe, and a few others.
  socialIcons:
    - name: github
      url: "https://github.com/kevinmingtarja"
    - name: linkedin
      url: "https://linkedin.com/in/kevinmingtarja/"
    - name: twitter
      url: "https://twitter.com/kevin_mingtarja"
    - name: email
      url: "mailto:kevin.mingtarja@gmail.com"
#   analytics:
#     google:
#       SiteVerificationTag: "XYZabc"
#     bing:
#       SiteVerificationTag: "XYZabc"
#     yandex:
#       SiteVerificationTag: "XYZabc"

#   editPost:
#     URL: "https://github.com/<path_to_repo>/content"
#     Text: "Suggest Changes" # edit text
#     appendFilePath: true # to append file path to Edit link

#   # for search
#   # https://fusejs.io/api/options.html
#   fuseOpts:
#     isCaseSensitive: false
#     shouldSort: true
#     location: 0
#     distance: 1000
#     threshold: 0.4
#     minMatchCharLength: 0
#     keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Search
      name: Search
      url: /search/
      weight: 30
# # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#   highlight:
#     noClasses: false
#     # anchorLineNos: true
#     # codeFences: true
#     # guessSyntax: true
#     # lineNos: true
#     # style: monokai

outputs:
  home:
    - HTML
    - JSON

deployment:
  targets:
    - name: "s3"
      URL: "s3://prod-kevinmingtarja-com?region=us-east-1"
      cloudFrontDistributionID: "E11SQTXFGM2CXB"
